source = ~/.config/hypr/parts/defaults.conf
source = ~/.config/hypr/parts/startup.conf
source = ~/.config/hypr/parts/envvar.conf

source = ~/.config/hypr/parts/monitors.conf
source = ~/.config/hypr/parts/general.conf
source = ~/.config/hypr/parts/misc.conf
source = ~/.config/hypr/parts/windowrules.conf

source = ~/.config/hypr/parts/input.conf
source = ~/.config/hypr/parts/gestures.conf
source = ~/.config/hypr/parts/keybindings.conf

source = ~/.config/hypr/parts/animations.conf
source = ~/.config/hypr/parts/decorations.conf
source = ~/.config/hypr/parts/theme.conf

