$main_mod = SUPER

$terminal = kitty
$file_manager = nautilus
# $menu = pkill wofi || wofi --show drun # Toggleable wofi window
$menu = vicinae toggle
$clipboard = vicinae vicinae://extensions/vicinae/clipboard/history
$notifications_menu = swaync-client -t -sw
# $redEyeFilter = gammastep -x || gammastep -O 4500
# $redEyeFilter = pkill hyprsunset || hyprsunset -t 4500 # Toggleable blue light filter

$grim_dir = ~/Pictures/grim-screenshots

$eye_filter = ~/.config/hypr/scripts/blue-light-filter.sh
$gamemode = ~/.config/hypr/scripts/gamemode.sh
$toggle_mic = ~/.config/hypr/scripts/toggle-mic.sh
$toggle_speakers = ~/.config/hypr/scripts/toggle-speakers.sh
$full_screenshot = ~/.config/hypr/scripts/full-screenshot.sh
$region_screenshot = ~/.config/hypr/scripts/region-screenshot.sh
