# See https://wiki.hyprland.org/Configuring/Variables/ for more
general {

    gaps_in = 5
    gaps_out = 20
    border_size = 2

    layout = dwindle

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false
}



group:groupbar:font_size = 12
group:groupbar:height = 15



# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}



# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    # new_is_master = true
}

