# https://wiki.hypr.land/Configuring/Gestures/
gestures {
    # https://github.com/hyprwm/Hyprland/pull/11490
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    # workspace_swipe = on
    gesture = 3, horizontal, workspace
    # gesture = 3, horizontal, mod: SUPER, move
}

