# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    # English (Default), Serbian (Latin), Serbian (Cyrillic)
    kb_layout = us, rs, rs
    kb_variant = , latin,
    kb_model =
    kb_options = grp:win_space_toggle # Switching on WIN + Space
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}
