# See https://wiki.hyprland.org/Configuring/Variables/ for more
misc {
    #force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    vfr = true
    disable_autoreload = true
    disable_hyprland_logo = true
    middle_click_paste = false
}

