exec-once = vicinae server
exec-once = hyprpaper 
exec-once = LC_TIME="sr_RS.UTF-8" waybar # must change env variable LC_TIME to make mondays as the first day of the week
# exec = ~/Games/xava-x86_64.AppImage -p ~/.config/xava/config # This takes battery; not suitable power savings & high performanceÔ
exec-once = swaync
exec-once = mkfifo /tmp/wobpipe; tail -f /tmp/wobpipe | wob

